### PR TITLE
Added remove_isolated_nodes (#327)

### LINKED ISSUE #327: use pyg `remove_isolated_nodes` instead of custom implementation

### PR DESCRIPTION
**Pull request by jnpark3**
Incorporated remove_isolated_nodes into the code for the track condensation networks.

Fixes #327

### CODE REVIEW

**Comment by jnpark3** [comment]
pre-commit.ci autofix

**Review by klieret — APPROVED** [review]

**Comment by jnpark3** [comment]
Edit was made to the first commit because edge features do not need to be updated since there are no loops (not affected by labeling).

**Comment by jnpark3** [comment]
pre-commit.ci autofix

**Comment by jnpark3** [comment]
pre-commit.ci autofix

**Comment by jnpark3** [comment]
pre-commit.ci autofix

**Comment by klieret** [comment]
@all-contributors please add @jnpark3 for code

**Pull request merged**
