### PR TITLE
Create tests for utils/plotting.py (#302)

### PR DESCRIPTION
**Pull request by kingjuno**
This PR creates tests for #302.

### CODE REVIEW

**Comment by kingjuno** [comment]
@klieret For now, I have only created tests for `EventPlotter` to confirm whether I am doing things correctly. If so, I will start working on the others.

**Review by klieret — APPROVED** [review]
Thanks a lot for all of your work. I'm impressed by how thoroughly you started this. I was mostly thinking about ensuring that the plots run without failure, rather than testing the results.

This is also where I see the following issue: We duplicate a lot of code from the `EventPlotter`. That means we test that we get the same result with the code copied over from its origin (with the intermediate step of plotting it and retrieving it again), which then doesn't show all that much.

So while I can see that a lot of thinking went into this, would you be open to simplifying this?

So we could do something really silly, like just testing `len(fig.axes[i].get_lines()[0].get_xydata()))`.

If we want to test the content, we could simply do something like

`fig.axes[i].get_lines()[0].get_xydata()[0] == approx(hard coded number here)`

**Comment by kingjuno** [comment]
So I am assuming that you need the test to look something like this.
```python
def test_event_plotter(mock_show):
    assert mock_show is plt.show
    path = trackml_test_data_dir
    evtid = 1

    plotter = EventPlotter(indir=path)
    fig, _ = plotter.plot_ep_rv_uv(evtid=evtid)
    original_data_points = []

    original_data_points.append(
        [
            [-3.65964174, -2.99420524],
            [-3.14542103, -2.94588566],
            [-3.65947032, -2.99451041],
            [-3.14519644, -2.94551826],
            [-2.90377235, -2.63840151],
            [-3.21849656, -2.51005006],
            [-3.2187562, -2.50965071],
            [-3.48590827, -2.21800613],
            [-2.85355783, -2.35087061],
            [-3.21562123, -2.23991871],
        ]
    )
    original_data_points.append(
        [
            [-1502.5, 77.40522003],
            [-1498.0, 129.21363831],
            [-1498.0, 77.18669128],
            [-1502.0, 129.58804321],
            [-1498.0, 164.72381592],
            [-1502.0, 120.39829254],
            [-1498.0, 120.04631805],
            [-1498.0, 91.84147644],
            [-1502.0, 173.72445679],
            [-1498.0, 120.42472839],
        ]
    )
    original_data_points.append(
        [
            [-0.01277896, -0.00189722],
            [-0.00759138, -0.00150495],
            [-0.01281572, -0.00189868],
            [-0.0075689, -0.00150338],
            [-0.00531829, -0.00292747],
            [-0.00670373, -0.00490364],
            [-0.00672142, -0.00492071],
            [-0.00656526, -0.00868637],
            [-0.00404855, -0.00409189],
            [-0.00515092, -0.00651333],
        ]
    )
    for i in range(3):
        assert_almost_equal(
            np.array(fig.axes[i].get_lines()[0].get_xydata()[:2]),
            np.array(original_data_points[i])[:2],
        )
    plt.close(fig)
```

**Comment by klieret** [comment]
Yes, I think that looks perfect :) 

Some code quality checkers will probably want you to define `original_data_points` in one go (rather than appending to it).

I propose to merge this once you're done with this test and to create a new PR for any other tests.

**Comment by kingjuno** [comment]
I have pushed the changes. Let me know if any changes are required.

**Review by klieret — APPROVED** [review]
Looks good to me! Thank you so much :) 

I'll merge once the tests run through

```

        for i in range(3):
>           assert_approx_equal(
                np.array(fig.axes[i].get_lines()[0].get_xydata()[:10]),
                np.array(original_data_points[i]),
            )

src/gnn_tracking/utils/test_plotting.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (array([[-3.65964174, -2.99420524],
       [-3.14542103, -2.94588566],
       [-3.65947032, -2.99451065],
       [-3.1...2.50965071],
       [-3.48590827, -2.21800613],
       [-2.85355783, -2.35087061],
       [-3.21562123, -2.23991871]]))
kwds = {}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           TypeError: only size-1 arrays can be converted to Python scalars
```

I don't immediately see the route course, does this happen locally?

**Comment by kingjuno** [comment]
oops test failed because I forgot to change `approx_equal` to `almost_equal` :smiling_face_with_tear:  .

**Comment by klieret** [comment]
@all-contributors please add @kingjuno for test

**Comment by klieret** [comment]
@all-contributors please add @kingjuno for test

**Comment by klieret** [comment]
Hmmm :/   I wonder if I broke the `.all-contributorsrc`...

**Pull request merged**
